name: deluxe waffle
on:
  push:
    branches:
      - main
  schedule:
    - cron: "55 15 * * 0" # 4PM GMT Sunday - 5min
jobs:
  waffle:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Installed package list
        run: apt list --installed
      - name: Remove Chrome
        run: sudo apt purge google-chrome-stable
      - name: Remove default Chromium
        run: sudo apt purge chromium-browser
      - name: Install a new Chromium
        run: sudo apt install -y chromium-browser
      - name: Install all necessary packages
        run: pip install -r setup/requirements.txt
      - name: Solve Deluxe Waffle :)
        run: python main.py 2
