name: deluxe waffle
on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * 0" # 4PM GMT Sunday
jobs:
  waffle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Chrome setup matters
        run: |-
          apt list --installed
          sudo apt purge google-chrome-stable
          sudo apt purge chromium-browser
          sudo apt install -y chromium-browser
          chromium-browser --version > version.txt
          pip install -r requirements.txt
      - name: Solve deluxe Waffle :)
        run: python telegram.py 2
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHATS: ${{ secrets.CHATS }}
