name: daily waffle
on:
  workflow_dispatch:
  schedule:
    - cron: "45 15 * * *" # 4PM GMT - 15min
jobs:
  waffle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Chrome setup matters
        run: |-
          apt list --installed
          sudo apt purge google-chrome-stable
          sudo apt purge chromium-browser
          sudo apt install -y chromium-browser
          pip install -r requirements.txt
      - name: Solve daily Waffle :)
        run: python telegram.py -m 1 -c 1
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHATS: ${{ secrets.CHATS }}
